/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaOrientacaoObjeto;

import static java.time.Clock.system;
import static java.time.InstantSource.system;

public class App {
   

    public static void main(String[] args) {
        
          /* ENCAPSULAMENTO
       
       Pessoa pes = new Pessoa();
       
       pes.setNome("Laidson Saturnino");
       pes.setIdade(20);
       System.out.println(pes.toString());
      */
          
        /*HERANÇA  
      pessoaFisica fis = new pessoaFisica();
      
      pessoaJuridica jur = new pessoaJuridica();
      
       fis.nome = "Laidson Saturnino";
       fis.cpf = "1111111111";
       fis.identidade = "123489794";
       fis.situacaoPessoa= "A";
       
       
       
       jur.cnpj = "3412543252352345";
       jur.nome = "Casas Bahia";
       jur.inscEstadual = "3435543534";
       jur.situacaoPessoa = "I";
       
       System.out.println("Dados Pessoa Fisica");
       System.out.println(fis.toString());
       
       System.out.println("Dados Pessoa Juridica");
       System.out.println(jur.toString());
*/
       
       // POLIMORFISMO
    
    Mamifero mamifero1 = new Elefante();
    Mamifero mamifero2 = new Rato();
    
    System.out.println("Cota diária de leite de um Elefante: " + mamifero1.cotaDiariaLeite() + " litros");
    System.out.println("Cota diária de leite de um Rato: " + mamifero2.cotaDiariaLeite() + " litros");
       
       
      
    }
}
